### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by ChrisF999** [lntel/Quickcord#11]
**Describe the bug**
Images do not load in embeds 
**To Reproduce**

     const embed = Quickcord.Embed({
          image: json.url
          });
          res.channel.send(embed);
no error appears but no image will be set in the embed 
**Expected behavior**
Image appears in the embed
**Screenshots**
https://cdn.discordapp.com/attachments/616750700541640734/677260519274709013/unknown.png
**Additional context**

**Comment by lntel** [comment]
After some brief testing, I discovered that the `RichEmbed` constructor does not accept a couple of the properties such as `image` and `thumbnail`. Therefore, I will implement this fix shortly.

**Comment by lntel** [comment]
So after looking into this issue, I found out that instead of providing simply the URL within the `image` property, you must provide an object. This object can contain a few different properties as listed below.
* url
* proxy_url
* height
* width

For your use case, you could do the following:
```js
const embed = Quickcord.Embed({
    image: {
        url: json.url
    }
});
```
